
name: Rollout Django deployment

on:
  workflow_call:
  workflow_dispatch:
jobs:
  rollout:
    runs-on: ubuntu-latest
    env:
      CLUSTER_NAME: k8s-prostore
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_TOKEN_KEY }}
      - name: cluster kubeconfig file
        run: |
          doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ env.CLUSTER_NAME }}
      - name: Rollout on deployment
        run: |
          kubectl rollout restart deployment/deeptest-deployment
